services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db-entrypoint:/docker-entrypoint-initdb.d
  api:
    build:
      context: api
      args:
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}?schema=public"
    ports:
      - ${PRISMA_STUDIO_PORT}:5555
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${APP_PORT}:80