services:

  api:
    build:
      context: api
      args:
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}?schema=public"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${PRISMA_STUDIO_PORT}:5555
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${APP_PORT}:80

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.13.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${DIRECTUS_PORT}:8055
    volumes:
      - ./data/uploads:/directus/uploads
      - ./data/extensions:/directus/extensions
    depends_on:
      - cache
    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: "pg"
      DB_HOST: ${DB_HOST}
      DB_PORT: "5432"
      DB_DATABASE: "greenbook"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_USER}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASS}

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}